# Generated by Django 4.0.6 on 2022-11-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_user'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='profile',
            name='user_profil_name_54fbe0_idx',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='user_profil_user_id_4f95f8_idx'),
        ),
    ]
