# Generated by Django 4.0.6 on 2022-11-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_remove_profile_user'),
        ('blog', '0002_alter_blog_author_alter_comment_blog_user_id_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('order', '0002_alter_card_user_id_alter_wish_list_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name'], name='user_user_first_n_45e159_idx'),
        ),
    ]
