# Generated by Django 4.0.6 on 2022-11-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
