# Generated by Django 4.0.6 on 2022-11-25 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_shippingaddress_company_name_and_more'),
        ('user', '0011_profile_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
