# Generated by Django 4.0.6 on 2022-11-26 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_remove_product_digital'),
        ('blog', '0003_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
    ]
