# Generated by Django 4.0.6 on 2022-11-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderitem_shippingaddress_remove_order_card_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(choices=[('Azerbaijan', 'Azerbaijan'), ('Turkey', 'Turkey'), ('USA', 'USA')], default='Azerbaijan', max_length=200),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
