# Generated by Django 4.0.6 on 2022-11-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_shippingaddress_country_alter_shippingaddress_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='company_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
