# Generated by Django 4.1 on 2022-10-19 08:11

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('LOUIS', 'LOUIS'), ('GUCCI', 'GUCCI'), ('HERMES', 'HERMES'), ('PRADA', 'PRADA'), ('CHANEL', 'CHANEL'), ('RALPH', 'RALPH'), ('BURBERRY', 'BURBERRY'), ('HOUSE', 'HOUSE'), ('FENDI', 'FENDI'), ('NIKE', 'NIKE')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Tshirt', 'Tshirt'), ('Shorts', 'Shorts'), ('Hoodie', 'Hoodie'), ('Skirt', 'Skirt'), ('Cap', 'Cap'), ('Dress', 'Dress'), ('Jeans', 'Jeans'), ('Shoes', 'Shoes'), ('Coat', 'Coat'), ('Suit', 'Suit'), ('Hat', 'Hat'), ('Socks', 'Socks'), ('Gloves', 'Gloves'), ('Scarf', 'Scarf'), ('Tie', 'Tie'), ('Swimsuit', 'Swimsuit'), ('Gym clothes', 'Gym clothes')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('orange', '#FFA500'), ('black', '#000000'), ('blue', '#0000FF'), ('pink', '#FFC0CB'), ('grey', '#808080'), ('green', '#00FF00'), ('brown', '#964B00'), ('purple', '#800080'), ('red', '#EE4B2B'), ('white', '#FFFFFF'), ('yellow', '#FFFF00')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='products')),
                ('desc', models.TextField()),
                ('last_price', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('TREND', 'TREND'), ('OUT OF STOCK', 'OUT OF STOCK'), ('BEST BRAND', 'BEST BRAND')], max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('3XL', '3XL'), ('4XL', '4XL'), ('5XL', '5XL')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=50)),
                ('rating', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1)),
                ('email', models.CharField(max_length=50)),
                ('published_date', models.DateTimeField(default=datetime.datetime(2022, 10, 19, 12, 11, 47, 165510))),
                ('product_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.size'),
        ),
    ]
