# Generated by Django 4.1 on 2022-10-19 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productreview_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='productreview',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 19, 12, 46, 40, 54693)),
        ),
    ]
