# Generated by Django 4.1 on 2022-10-19 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_productreview_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='user',
        ),
        migrations.AlterField(
            model_name='productreview',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 19, 12, 49, 23, 61945)),
        ),
    ]
