# Generated by Django 4.0.6 on 2022-11-01 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productreview_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 11, 55, 47, 503725)),
        ),
    ]
