# Generated by Django 4.0.6 on 2022-11-01 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productreview_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='product_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 15, 2, 18, 507907)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=5),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review',
            field=models.CharField(max_length=20),
        ),
    ]
