# Generated by Django 4.0.6 on 2022-11-01 11:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productreview_product_id_alter_productreview_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 15, 6, 17, 861596)),
        ),
    ]
