# Generated by Django 4.0.6 on 2022-11-01 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productreview_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
