# Generated by Django 4.0.6 on 2022-11-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_productreview_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_de',
            field=models.CharField(choices=[('Tshirt', 'Tshirt'), ('Shorts', 'Shorts'), ('Hoodie', 'Hoodie'), ('Skirt', 'Skirt'), ('Cap', 'Cap'), ('Dress', 'Dress'), ('Jeans', 'Jeans'), ('Shoes', 'Shoes'), ('Coat', 'Coat'), ('Suit', 'Suit'), ('Hat', 'Hat'), ('Socks', 'Socks'), ('Gloves', 'Gloves'), ('Scarf', 'Scarf'), ('Tie', 'Tie'), ('Swimsuit', 'Swimsuit'), ('Gym clothes', 'Gym clothes')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(choices=[('Tshirt', 'Tshirt'), ('Shorts', 'Shorts'), ('Hoodie', 'Hoodie'), ('Skirt', 'Skirt'), ('Cap', 'Cap'), ('Dress', 'Dress'), ('Jeans', 'Jeans'), ('Shoes', 'Shoes'), ('Coat', 'Coat'), ('Suit', 'Suit'), ('Hat', 'Hat'), ('Socks', 'Socks'), ('Gloves', 'Gloves'), ('Scarf', 'Scarf'), ('Tie', 'Tie'), ('Swimsuit', 'Swimsuit'), ('Gym clothes', 'Gym clothes')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_tr',
            field=models.CharField(choices=[('Tshirt', 'Tshirt'), ('Shorts', 'Shorts'), ('Hoodie', 'Hoodie'), ('Skirt', 'Skirt'), ('Cap', 'Cap'), ('Dress', 'Dress'), ('Jeans', 'Jeans'), ('Shoes', 'Shoes'), ('Coat', 'Coat'), ('Suit', 'Suit'), ('Hat', 'Hat'), ('Socks', 'Socks'), ('Gloves', 'Gloves'), ('Scarf', 'Scarf'), ('Tie', 'Tie'), ('Swimsuit', 'Swimsuit'), ('Gym clothes', 'Gym clothes')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_zn_ch',
            field=models.CharField(choices=[('Tshirt', 'Tshirt'), ('Shorts', 'Shorts'), ('Hoodie', 'Hoodie'), ('Skirt', 'Skirt'), ('Cap', 'Cap'), ('Dress', 'Dress'), ('Jeans', 'Jeans'), ('Shoes', 'Shoes'), ('Coat', 'Coat'), ('Suit', 'Suit'), ('Hat', 'Hat'), ('Socks', 'Socks'), ('Gloves', 'Gloves'), ('Scarf', 'Scarf'), ('Tie', 'Tie'), ('Swimsuit', 'Swimsuit'), ('Gym clothes', 'Gym clothes')], max_length=50, null=True),
        ),
    ]
