# Generated by Django 4.0.6 on 2022-11-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_category_name_alter_category_name_de_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_zn_ch',
        ),
    ]
