# Generated by Django 4.0.6 on 2022-11-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_category_name_zn_ch'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_time',
            field=models.IntegerField(default=0),
        ),
    ]
