# Generated by Django 4.0.6 on 2022-11-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_purchase_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('WOMEN', 'WOMEN'), ('MEN', 'MEN')], default='WOMEN', max_length=10),
        ),
    ]
