# Generated by Django 4.0.6 on 2022-11-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('WOMEN', 'WOMEN'), ('MEN', 'MEN')], default='WOMEN', max_length=10),
        ),
    ]
