# Generated by Django 4.0.6 on 2022-11-22 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_category_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='gender',
        ),
    ]
