# Generated by Django 4.0.6 on 2022-11-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_productimagedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('TREND', 'TREND'), ('OUT OF STOCK', 'OUT OF STOCK'), ('BEST BRAND', 'BEST BRAND'), ('SOON', 'SOON')], max_length=50),
        ),
    ]
