# Generated by Django 4.0.6 on 2022-11-24 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_product_digital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
