# Generated by Django 4.1 on 2022-10-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creative_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('facebook', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('google', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('mdi_dribbble', models.CharField(max_length=100)),
            ],
        ),
    ]
