# Generated by Django 4.0.6 on 2022-11-22 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_collection_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
