# Generated by Django 4.0.6 on 2022-11-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_creative_team_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('phone_number', models.EmailField(max_length=128)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
